name = "BrickOwl"
uuid = "62b12a7f-1817-4d2f-9aad-ff89de8a0f4b"
authors = ["Bernhard König <github@diro.ch> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
